### ISSUE TITLE
New Logo Design For Blade Player

### ISSUE THREAD

**Issue by zularizal** [Valou3433/blade-player#1]
Hi @Valou3433 , I want to contribute to your project, I want to design a logo and icon for the app and it's free, do you want it?

**Comment by Valou3433** [comment]
Sure if you want to design a new logo, I'll be happy to include it on the app.
I'm a pretty bad designer and i did the actual logo with android clipart images and android studio, so it would be cool to have our own logo :)
You can do it when you want !

**Comment by zularizal** [comment]
Okay, I'm designing it

**Comment by zularizal** [comment]
Okay, I've made it, do you like it? if you want a change, do not hesitate to tell me.

![logo](https://user-images.githubusercontent.com/38547278/39963042-df263ac2-568a-11e8-9f5a-25273c57cee1.png)

**Comment by Valou3433** [comment]
Maybe it looks like the bluetooth logo ? If you could change 1 or 2 little things to make it more original, that could be nice :)
Anyway i'll integrate it on the next release, but i will also need a Notification Icon, that can only be black without background (look https://developer.android.com/guide/practices/ui_guidelines/icon_design_status_bar )

**Comment by zularizal** [comment]
How about this?
![ex](https://user-images.githubusercontent.com/38547278/39965927-ccdc3c08-56cc-11e8-8e84-ee4753422112.png)

**Comment by Valou3433** [comment]
That's so nice ! :)
Could you send me the individual image so that i can integrate it right now ?

**Comment by zularizal** [comment]
Okay I'll upload it to drive, wait a moment
