### ISSUE TITLE
Adding a song to current playlist crashes the app

### ISSUE THREAD

**Issue by neupanedipen** [Valou3433/blade-player#13]
#### Expected behavior<br>
I should be able add songs to current playlist on clicking the option.<br>
#### Actual behavior<br>
But the app crashes on adding a song to current playlist.<br>
#### How to reproduce<br>
1. Install the app and launch it. <br>
2. Go to songs option. Click on three vertical dots next to any song and click &quot;Add to current playlist&quot; option.<br>
The app crashes.<br>
* App Version: 0.6<br>
* Device: Samsung Galaxy J5<br>
* Operating System: Android 6.0.1<br>
#### Recording Of The Bug<br>
https://youtu.be/EKMe2JOHCMU

**Comment by Valou3433** [comment]
This is the same issue as #10 , and i already fixed it in my development version ; it will come in the 0.7 pre-release ! Thanks for reporting anyway ! :)
