### ISSUE TITLE
Licenses of libraries

### ISSUE THREAD

**Issue by Poussinou** [Valou3433/blade-player#20]
Hi,

Do you know the exact licenses of `com.spotify.android:auth:1.0.0-alpha`, `com.github.kaaes:spotify-web-api-android:0.4.1`, `com.spotify.sdk:spotify-player-24-noconnect-2.20` and `com.deezer.sdk:deezer-sdk-0.11.2`?

The goal would be to include this app in [F-Droid](https://f-droid.org/), if you're ok.

**Comment by Valou3433** [comment]
The license of com.spotify.android:auth:1.0.0-alpha is Apache 2.0 ; the licence of com.github.kaaes:spotify-web-api-android:0.4.1 is MIT licence. However i'm really unsure about com.spotify.sdk:spotify-player-24-noconnect-2.20, and i'm pretty sure that com.deezer.sdk:deezer-sdk-0.11.2 is closed-source, so F-Droid won't be happy...
Anyway those services (spotify and deezer) are collecting data from the user and i don't think that F-Droid will allow that...
That would be a nice idea but i think it will be impossible, and after that, even if i thought that the app was ready for the 'real world', it looks like there are still lots of bugs... (and i can't really fix them now as i'm supposed to work on my exams)

**Comment by Poussinou** [comment]
Hum yes it will be hard to include an app with such problems about library licenses...

Spotify and Deezer track their users, but your app doesn't... Your app would have a "use non free network services" marker indeed...

I'll close this issue for now, maybe reopen it later if the licenses change and your app is totally ready for production if you want ;)

@izzysoft Is it suitable for your own repo? :)

Bonne chance pour tes exams 👍

**Comment by Poussinou** [comment]
@IzzySoft I think your description is clear enough :)

(Sorry, I didn't opened an issue on your gitlab repo, like you want me to do^^)

**Comment by IzzySoft** [comment]
OK, then it stays that way. And no worries, it was in the flow here :wink:
