### ISSUE TITLE
Frequently Asked Question (FAQ) Proposal 

### ISSUE THREAD

**Issue by olayhemy** [Valou3433/blade-player#22]
Hello there, I'd like to contribute to your awesome project by writing a Frequent Asked Questions (FAQ) for users self-service. Would love to hear from you, thanks

**Comment by Valou3433** [comment]
That is a nice idea ! I could put that on project wiki !
You can start with questions like https://github.com/Valou3433/blade-player/issues/21, which i'm sure are frequents...
Also please mention that the application is really a project that i do for me, so i can't test it everywhere, or assure that there will be no bugs/crashes...
Anyway i would love to have that :)

**Comment by olayhemy** [comment]
Thanks for the reply! 

I've pulled a PR for the FAQ, kindly merge!

**Comment by Valou3433** [comment]
Looks good to me ; i merged ! There are typos in your file i believe (Deever instead of Deezer, ...) but i'll fix them on next commit, don't worry...
