### ISSUE TITLE
Documentation contribution to blade music player.

### ISSUE THREAD

**Issue by HarryHeights** [Valou3433/blade-player#24]
Hello, I'm Harry. Blade-Player is really cool having utilized it for few days now. I'll like to make documentation contributions to your project. I noticed your readme document contains mostly pictures and doesn't give prospective users in-depth knowledge of the app, I'll work on the readme document and include more details about the app. Furthermore, I could create a privacy policy document that will enlighten users about how their information while using the music player is handled and utilized. 
My documentation will include;
- Improved readme
- Privacy Policy
- About Us (Brief information about the project and developer)
- Contact Us (How you can be contacted).

Hope to hear from you soon. Thanks.

**Comment by Valou3433** [comment]
Well i'm happy to hear that from you, and of course if you want to contribute you're always welcome !

**Comment by HarryHeights** [comment]
Alright. Thanks for the opportunity. During the course of my contribution however, I'll go over some things with you to create a perfect document. So I'll be needing some information from you.

The information I'll need is for the privacy policy document. Privacy policy will create transparency between you as the developer and then prospective users as to what information you collect when they use the app and how the collected information is utilized. 

I'll need those details to create the perfect document.

Thanks for your time.

**Comment by Valou3433** [comment]
Well i only collect user data when Blade crashes, and i only get stack strace and basic device information (using the ACRA library). I plan to add a disable button for this feature in the future but for now i need reports to fix bugs (as the app is still young). However, i really don't know how Spotify and Deezer collect data from the user...

**Comment by HarryHeights** [comment]
Okay, I'll include the spotify and deezer issue as third party dependencies but you are not aware of the data they collect. Then I'll have to make a disclaimer too.

I'll get to work with the document right away. When I'm done I'll make pull requests.

**Comment by HarryHeights** [comment]
Hello good day.. I'm done with creating the document I proposed. I've worked on the Readme file and added details to it. I also created a new privacy policy document which will need your review as there maybe some content that are not desirable by you in the document.  You can make those changes yourself or I could do it if you don't have the time to.

Thanks. Will be anticipating your response.

**Comment by Valou3433** [comment]
Hi ! Sorry for not being so active lately but i have other things to work on and i can't get an internet connection every day...
I've read your documents and they look fine, maybe i'll change one or two things after (like adding technical details to the privacy policy, on how we collect data or connect to spotify/deezer) but thats all.
I approved your pull requests and merged them to master, thanks for your contribution !
Other people that contributed where : 
- zularizal, who made the logo
- olayhemy, who made the FAQ document (i'll add a link to that in the readme.md later, it is in the root tree as FAQ.md)
- and you, for the privacy policy and improved documentation
I'm the only developer of the project, at least for the moment...
Anyway to me we can close this issue, everything seems good so far ; is there anything else you want to talk about / add to the project ?

**Comment by Valou3433** [comment]
Yeah i'm working on more features, tag editor and themes should be on the next release (if i have time and motivation). Lyrics reader was not planned but i could add that in the future ; i will also need to work on the multiple bugs that the app still has, even if some come from the spotify/deezer apis and i can't really do anything about theses...
I also thought about integrating a "comunity" thing that could let you look at your friend's playlist (spotify and deezer friends) or something like that, and a place to control spotify remote....
After that i would like to keep the app small in terms of memory consumption ; the interface and the whole project was also built because i did not really like Spotify/Deezer app as they were really heavy, and i'm building this with the KISS philosophy in mind.

**Comment by HarryHeights** [comment]
Yea small memory consumption is vital these days. I hate heavy apps. It's one of the reasons I utilize your music player even more than my stock music player. Then the idea about peeking on a friend's playlist is awesome, I think that would even make this project a lil more fancier and will attract more users. 
I honestly can't wait for these features to be implemented. In the meantime you can work on easier features like the themes. I really love dark themes. I saw you already opened an issue for it. 
Btw what kind of motivation would you be needing to make these changes?
