### ISSUE TITLE
The app is crashing for deleting the newly/latest created playlist

### ISSUE THREAD

**Issue by sagorahmed** [Valou3433/blade-player#32]
#### Actual behavior
The application crashes when I try to delete the newly created playlist.

#### Expected behavior
The users should be able to delete the playlist successfully without the crashing.

#### How to reproduce
1. Open the app and go to the "Songs" menu.
2. Choose a song and click on ⋮ (Three dots/ Vertical ellipsis) at the side of the song.
3. Then click on "Add to playlist".
4. After that click on the"New Playlist" to create a new playlist.
5. Give a name and click ok. (Your playlist will successfully be created)
6. Then delete your newly created playlist.
7. See error.

* App version: v1.4.0.1
* Device: Samsung A5
* Operating system: Android 6.0.1

#### Recording Of The Bug
![bladebug](https://media.giphy.com/media/Y48QifyMNlc2uCePAC/giphy.gif)

#### Logcat
```
D AndroidRuntime: Shutting down VM

04-03 14:53:04.258 30746 30746 E AndroidRuntime: FATAL EXCEPTION: main

04-03 14:53:04.258 30746 30746 E AndroidRuntime: Process: v.blade, PID: 30746

04-03 14:53:04.258 30746 30746 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference

04-03 14:53:04.258 30746 30746 E AndroidRuntime: 	at v.blade.library.sources.Source$1.removePlaylist(Source.java:462)

04-03 14:53:04.258 30746 30746 E AndroidRuntime: 	at v.blade.ui.MainActivity$4$1$2.onClick(MainActivity.java:316)

04-03 14:53:04.258 30746 30746 E AndroidRuntime: 	at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:166)

04-03 14:53:04.258 30746 30746 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)

04-03 14:53:04.258 30746 30746 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)

04-03 14:53:04.258 30746 30746 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7325)

04-03 14:53:04.258 30746 30746 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)

04-03 14:53:04.258 30746 30746 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)

04-03 14:53:04.258 30746 30746 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by Valou3433** [comment]
Thanks for the report ! This should be easy to fix. Will be fixed in next release for sure.

**Comment by sagorahmed** [comment]
Hello @Valou3433, Thanks for your response. Glad you want it to be fixed and hope that you will release the latest version as soon as possible with more flexibility.
Best regards,
Sagor Ahmed

**Comment by maaudrana** [comment]
@sagorahmed vai
 ami adb tools diye log capture korte peresi but akhon bujte parsi na kon ongso tuku testing app er  log.ami jta capture koresi seta onek long.pray 700kb+ hoye jay log file ta...er modde theke apni j log tuku akhane diyesen seta kivabe.
noito apni jodi blten apni ki use kore logcat capture koren ,process ta ki tahole onek upokrito hotam.
Thanks
