### ISSUE TITLE
Error during playback (spotify)

### ISSUE THREAD

**Issue by HawkEy33** [Valou3433/blade-player#40]
Hello, I'm using v. 1.4 on android 9

I logged in with my free spotify account and can search for music, when I try to play anything it says "Error during playback".   Could it be that a premium account is required? 
Though, in browser I can play any song I like even with free account.

**Comment by Valou3433** [comment]
Unfortunately, to access songs with the Spotify API, you need a premium account.
As i do not work for or with Spotify AB, i have to use their API to connect to their servers.
So yes, you need a premium Spotify account to use Blade with Spotify, and i'm sorry, but i can't do anything about it...

**Comment by HawkEy33** [comment]
I see, thanks for the reply.
Might want to add that in the app description.
