### ISSUE TITLE
Add to playlist function does nothing .

### ISSUE THREAD

**Issue by kodeblacc** [Valou3433/blade-player#5]
#### Expected behavior
Blade-player offers the option to add tracks to playlist so it is expected that when the option is selected, the track is added to a playlist either automatically created since the app currently has no option to manually create playlist or allow users assign tracks to a playlist manually.
#### Actual behavior
\When the add to playlist option is selected, there is no toast message signifying if the operation was successful and the song is not added to any available playlist neither is a new playlist created.
#### How to reproduce
- Launch the app
- swipe from left to right to reveal menu
- click songs
- click 3 dots beside a track wished to be added to a playlist.
- click add to playlist option <hr>

* App name/App version: Blade Player v0.4
* Operating system:  Android 7.0

**Comment by Valou3433** [comment]
I'm sorry if you missunderstood the function, 'add to playlist' is actually 'add to current playlist', it adds the artist/album/song you selected to the current playlist only for this play session. I'll add real playlist edition on future updates, but to do that i'll need to implement local storage/spotify/deezer writing on user data, which i plan to do after i cleaned up the user library loading.
Anyway you're right i need to add a toast message, without that it really looks like doing nothing :)
Also just to let you know i'm happy to get issues like theses, so if you find bugs using Blade, dont worry you can always tell me, but remember that the project is still in pre-release (i started it 2 weeks ago).
