### ISSUE TITLE
App crashes during series of events

### ISSUE THREAD

**Issue by neupanedipen** [Valou3433/blade-player#6]
#### Series of events<br>
* Play a song<br>
* Click play on empty playlist<br>
* Click on album cover of playing song from below the playlist<br>
#### Expected Behaviour<br>
The app must be stable during the series of event of described on how to reproduce.<br>
#### Actual Behaviour<br>
But the app crashes during clicking on the song icon in playlist page when the song is playing.<br>
#### How to reproduce<br>
1. Launch the app and play any song.<br>
2. Now navigate to playlist option from left sliding menu.<br>
3. Click on three dots after the playlist name and click on play.<br>![](https://s19.postimg.cc/wcys9808j/20180524_003627.png)
It will not play anything.<br>
4. Now click on the song cover as appeared below the playlist.<br>
![](https://s19.postimg.cc/ok84h9her/20180524_003610.png)
The app crashes.<br>
* App Version: 0.5<br>
* Device: Samsung Galaxy J5<br>
* Operating System: Android 6.0.1<br>
#### Recording Of The Bug<br>
https://youtu.be/o6vb79kMvDA

**Comment by Valou3433** [comment]
Thanks for that report, i'm fixing it just now ! The problem was that i let the player try to play an empty playlist, which leads to a crash...
